-- ========================================================
-- PACKAUDIT STATUTORY DATABASE SCHEMA & SEED DATA
-- Legal Metrology Rules 2011, FSSAI 2020, & Textile 2011
-- ========================================================

CREATE TABLE IF NOT EXISTS rule_definitions (
    rule_id VARCHAR(50) PRIMARY KEY,
    rule_citation VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    check_type VARCHAR(50) NOT NULL,
    severity VARCHAR(20) DEFAULT 'MAJOR',
    fix_suggestion TEXT,
    validation_logic JSONB DEFAULT '{}'::jsonb
);

CREATE TABLE IF NOT EXISTS manufacturer_cache (
    id SERIAL PRIMARY KEY,
    company_name VARCHAR(255) NOT NULL,
    aliases JSONB DEFAULT '[]'::jsonb,
    registered_pincodes JSONB DEFAULT '[]'::jsonb,
    verified_addresses JSONB DEFAULT '[]'::jsonb
);

CREATE TABLE IF NOT EXISTS scans (
    id VARCHAR(36) PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    input_type VARCHAR(20) NOT NULL,
    image_path VARCHAR(255),
    authenticity_score FLOAT DEFAULT 100.0,
    object_classification VARCHAR(50) DEFAULT 'packaged_commodity',
    extracted_text TEXT
);

CREATE TABLE IF NOT EXISTS extracted_fields (
    id SERIAL PRIMARY KEY,
    scan_id VARCHAR(36) REFERENCES scans(id) ON DELETE CASCADE,
    field_name VARCHAR(50) NOT NULL,
    field_value TEXT,
    ocr_confidence FLOAT DEFAULT 1.0,
    bounding_box JSONB
);

CREATE TABLE IF NOT EXISTS rule_checks (
    id SERIAL PRIMARY KEY,
    scan_id VARCHAR(36) REFERENCES scans(id) ON DELETE CASCADE,
    rule_id VARCHAR(50) REFERENCES rule_definitions(rule_id),
    status VARCHAR(20) NOT NULL,
    explanation TEXT NOT NULL
);

-- SEEDING 25 STATUTORY RULE DEFINITIONS
INSERT INTO rule_definitions (rule_id, rule_citation, description, check_type, severity, fix_suggestion, validation_logic) VALUES ('check_1', 'Rule 18 Exemption Pre-Check', 'Checks if the product is exempt under Rule 18 (institutional/industrial use, net qty <= 10g/10ml, agricultural produce > 50kg, or export-only).', 'exemption', 'CRITICAL', 'Ensure statutory exemption eligibility criteria (net qty ≤ 10g/ml, agricultural produce > 50kg, or industrial/export use) are clearly documented on packaging.', '{"max_qty_exempt_g_ml": 10.0, "max_agricultural_produce_kg": 50.0}'::jsonb) ON CONFLICT (rule_id) DO UPDATE SET rule_citation = EXCLUDED.rule_citation, description = EXCLUDED.description, severity = EXCLUDED.severity, fix_suggestion = EXCLUDED.fix_suggestion, validation_logic = EXCLUDED.validation_logic;
INSERT INTO rule_definitions (rule_id, rule_citation, description, check_type, severity, fix_suggestion, validation_logic) VALUES ('check_2', 'Rule 6(1)(a)', 'Every package must bear the name and complete address of the manufacturer, packer, or importer.', 'presence', 'CRITICAL', 'Include the full legal name and complete postal address of the manufacturer/packer with a valid 6-digit PIN code.', '{"required_fields": ["manufacturer_name", "manufacturer_address"]}'::jsonb) ON CONFLICT (rule_id) DO UPDATE SET rule_citation = EXCLUDED.rule_citation, description = EXCLUDED.description, severity = EXCLUDED.severity, fix_suggestion = EXCLUDED.fix_suggestion, validation_logic = EXCLUDED.validation_logic;
INSERT INTO rule_definitions (rule_id, rule_citation, description, check_type, severity, fix_suggestion, validation_logic) VALUES ('check_3', 'Rule 6(1)(b)', 'The common or generic name of the commodity contained in the package must be declared.', 'presence', 'MAJOR', 'Declare the common or generic name of the packaged commodity prominently on the Principal Display Panel.', '{"required_fields": ["generic_name"]}'::jsonb) ON CONFLICT (rule_id) DO UPDATE SET rule_citation = EXCLUDED.rule_citation, description = EXCLUDED.description, severity = EXCLUDED.severity, fix_suggestion = EXCLUDED.fix_suggestion, validation_logic = EXCLUDED.validation_logic;
INSERT INTO rule_definitions (rule_id, rule_citation, description, check_type, severity, fix_suggestion, validation_logic) VALUES ('check_5', 'Rule 6(1)(d)', 'The month and year in which the commodity is manufactured or pre-packed or imported must be declared.', 'regex', 'MAJOR', 'Declare the month and year of manufacturing or pre-packing in standard format (e.g. ''08/2026'' or ''Aug 2026'').', '{"regex_pattern": "(?i)\\b(?:0[1-9]|1[0-2])[/\\-\\.](?:19|20)?\\d{2}\\b|\\b(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z]*\\s+(?:19|20)?\\d{2}\\b"}'::jsonb) ON CONFLICT (rule_id) DO UPDATE SET rule_citation = EXCLUDED.rule_citation, description = EXCLUDED.description, severity = EXCLUDED.severity, fix_suggestion = EXCLUDED.fix_suggestion, validation_logic = EXCLUDED.validation_logic;
INSERT INTO rule_definitions (rule_id, rule_citation, description, check_type, severity, fix_suggestion, validation_logic) VALUES ('check_6', 'Rule 6(1)(e)', 'The Maximum Retail Price (MRP) must be declared clearly, including the phrase ''inclusive of all taxes'' or ''incl. of all taxes''.', 'regex', 'CRITICAL', 'Add the mandatory statutory suffix ''inclusive of all taxes'' or ''incl. of all taxes'' immediately adjacent to the MRP declaration.', '{"required_phrases": ["inclusive of all taxes", "incl. of all taxes", "incl.of all taxes", "incl of all taxes"], "regex_pattern": "(?i)\\b(?:m\\.?r\\.?p\\.?|max\\.?(?:imum)?\\s*retail\\s*price)\\s*(?:rs\\.?|\u20b9)?\\s*\\d+(?:\\.\\d{2})?"}'::jsonb) ON CONFLICT (rule_id) DO UPDATE SET rule_citation = EXCLUDED.rule_citation, description = EXCLUDED.description, severity = EXCLUDED.severity, fix_suggestion = EXCLUDED.fix_suggestion, validation_logic = EXCLUDED.validation_logic;
INSERT INTO rule_definitions (rule_id, rule_citation, description, check_type, severity, fix_suggestion, validation_logic) VALUES ('check_7', 'Rule 6(1)(g)', 'Every package must bear the name, address, telephone number, and email address of the consumer care contact.', 'presence', 'MAJOR', 'Declare complete consumer care contact details including contact officer/cell name, postal address, working phone number, and valid email ID.', '{"required_fields": ["consumer_care_name", "consumer_care_phone", "consumer_care_email", "consumer_care_address"]}'::jsonb) ON CONFLICT (rule_id) DO UPDATE SET rule_citation = EXCLUDED.rule_citation, description = EXCLUDED.description, severity = EXCLUDED.severity, fix_suggestion = EXCLUDED.fix_suggestion, validation_logic = EXCLUDED.validation_logic;
INSERT INTO rule_definitions (rule_id, rule_citation, description, check_type, severity, fix_suggestion, validation_logic) VALUES ('check_8', 'Rule 6(1)(f)', 'For imported commodities and general goods, the country of origin must be declared.', 'presence', 'MAJOR', 'Declare the Country of Origin clearly on the packaging (e.g., ''Country of Origin: India'' or ''Made in India'').', '{"required_fields": ["country_of_origin"]}'::jsonb) ON CONFLICT (rule_id) DO UPDATE SET rule_citation = EXCLUDED.rule_citation, description = EXCLUDED.description, severity = EXCLUDED.severity, fix_suggestion = EXCLUDED.fix_suggestion, validation_logic = EXCLUDED.validation_logic;
INSERT INTO rule_definitions (rule_id, rule_citation, description, check_type, severity, fix_suggestion, validation_logic) VALUES ('check_9', 'Rule 6(1)(a) Importer', 'For imported commodities, the name and address of the importer must be declared.', 'presence', 'CRITICAL', 'For imported commodities, declare the registered company name and complete postal address of the Indian importer.', '{"required_fields": ["importer_name", "importer_address"]}'::jsonb) ON CONFLICT (rule_id) DO UPDATE SET rule_citation = EXCLUDED.rule_citation, description = EXCLUDED.description, severity = EXCLUDED.severity, fix_suggestion = EXCLUDED.fix_suggestion, validation_logic = EXCLUDED.validation_logic;
INSERT INTO rule_definitions (rule_id, rule_citation, description, check_type, severity, fix_suggestion, validation_logic) VALUES ('check_12', 'Rule 23 E-Commerce', 'For e-commerce sales, digital listing declarations must display all mandatory statutory fields.', 'presence', 'MAJOR', 'Ensure the digital marketplace listing displays all mandatory statutory declarations (MRP, Net Quantity, Country of Origin, Manufacturer details, Consumer care) matching physical label.', '{"fields_to_compare": ["mrp", "net_quantity", "manufacturer_name", "country_of_origin"]}'::jsonb) ON CONFLICT (rule_id) DO UPDATE SET rule_citation = EXCLUDED.rule_citation, description = EXCLUDED.description, severity = EXCLUDED.severity, fix_suggestion = EXCLUDED.fix_suggestion, validation_logic = EXCLUDED.validation_logic;
INSERT INTO rule_definitions (rule_id, rule_citation, description, check_type, severity, fix_suggestion, validation_logic) VALUES ('check_4', 'Rule 6(1)(c)', 'The net quantity, in terms of standard unit of weight, measure or number, must be declared.', 'measurement', 'CRITICAL', 'Declare net quantity using statutory metric unit symbols (''g'', ''kg'', ''ml'', ''l'', ''pcs'', ''N'') without non-standard abbreviations like ''gms'' or ''ltrs''.', '{"allowed_units": ["g", "grm", "gram", "grams", "kg", "kg.", "kilogram", "kilograms", "ml", "ml.", "milliliter", "milliliters", "l", "l.", "liter", "liters", "litre", "litres", "m", "meter", "meters", "pcs", "units", "u", "n", "pair", "pairs", "piece", "pieces"]}'::jsonb) ON CONFLICT (rule_id) DO UPDATE SET rule_citation = EXCLUDED.rule_citation, description = EXCLUDED.description, severity = EXCLUDED.severity, fix_suggestion = EXCLUDED.fix_suggestion, validation_logic = EXCLUDED.validation_logic;
INSERT INTO rule_definitions (rule_id, rule_citation, description, check_type, severity, fix_suggestion, validation_logic) VALUES ('check_10', 'Rule 6(3) / Font Height', 'Minimum font height of declarations must conform to the Principal Display Panel (PDP) area regulations.', 'measurement', 'MINOR', 'Increase letter and numeral font height to meet the minimum statutory height (e.g. min 2.0 mm for PDP area > 100 cm²) based on package surface area.', '{"pdp_font_rules": [{"max_area_cm2": 50, "min_height_mm": 1.0}, {"max_area_cm2": 100, "min_height_mm": 1.5}, {"max_area_cm2": 500, "min_height_mm": 2.0}, {"max_area_cm2": 1000, "min_height_mm": 3.0}, {"max_area_cm2": 999999, "min_height_mm": 4.0}]}'::jsonb) ON CONFLICT (rule_id) DO UPDATE SET rule_citation = EXCLUDED.rule_citation, description = EXCLUDED.description, severity = EXCLUDED.severity, fix_suggestion = EXCLUDED.fix_suggestion, validation_logic = EXCLUDED.validation_logic;
INSERT INTO rule_definitions (rule_id, rule_citation, description, check_type, severity, fix_suggestion, validation_logic) VALUES ('check_11', 'Rule 8 / Standard Sizes', 'Pre-packaged commodity net quantity must conform to the prescribed standard sizes for defined categories.', 'measurement', 'MAJOR', 'Pack the commodity in one of the prescribed standard net quantity sizes specified under the Second Schedule of Legal Metrology Rules.', '{"standard_sizes": {"tea": [25, 50, 75, 100, 125, 150, 200, 250, 500, 1000], "biscuits": [25, 50, 75, 100, 150, 200, 250, 300, 400], "edible_oil": [50, 100, 200, 250, 500, 1000, 2000, 3000, 5000], "soap": [25, 50, 75, 100, 125, 150], "water": [100, 150, 200, 250, 300, 500, 750, 1000, 1500, 2000, 5000]}}'::jsonb) ON CONFLICT (rule_id) DO UPDATE SET rule_citation = EXCLUDED.rule_citation, description = EXCLUDED.description, severity = EXCLUDED.severity, fix_suggestion = EXCLUDED.fix_suggestion, validation_logic = EXCLUDED.validation_logic;
INSERT INTO rule_definitions (rule_id, rule_citation, description, check_type, severity, fix_suggestion, validation_logic) VALUES ('fssai_check_1', 'FSSAI Sec 31 / License 3-Tier', 'Every food package must display a valid 14-digit FSSAI License/Registration number verified through mathematical syntax, FoSCoS portal, and state registry cache.', 'presence', 'CRITICAL', 'Obtain and declare a valid 14-digit FSSAI license/registration number with the official FSSAI logo on the Principal Display Panel.', '{"syntax_pattern": "^[12][0-3][0-9]\\d{11}$"}'::jsonb) ON CONFLICT (rule_id) DO UPDATE SET rule_citation = EXCLUDED.rule_citation, description = EXCLUDED.description, severity = EXCLUDED.severity, fix_suggestion = EXCLUDED.fix_suggestion, validation_logic = EXCLUDED.validation_logic;
INSERT INTO rule_definitions (rule_id, rule_citation, description, check_type, severity, fix_suggestion, validation_logic) VALUES ('fssai_check_2', 'FSSAI 2020 Reg 5(3) / Nutrition', 'Nutritional Information per 100g/100ml and per serving declaring Energy, Protein, Carbohydrates, Total/Added Sugars, Fat, Saturated/Trans Fat, and Sodium with mathematical consistency.', 'measurement', 'CRITICAL', 'Include a structured Nutritional Information table declaring all 8 mandatory nutrients per 100g/100ml and per serving.', '{"mandatory_nutrients": ["energy", "protein", "carbohydrates", "total_fat", "saturated_fat", "trans_fat", "sodium"]}'::jsonb) ON CONFLICT (rule_id) DO UPDATE SET rule_citation = EXCLUDED.rule_citation, description = EXCLUDED.description, severity = EXCLUDED.severity, fix_suggestion = EXCLUDED.fix_suggestion, validation_logic = EXCLUDED.validation_logic;
INSERT INTO rule_definitions (rule_id, rule_citation, description, check_type, severity, fix_suggestion, validation_logic) VALUES ('fssai_check_3', 'FSSAI 2020 Reg 5(4) / Veg Logo', 'Mandatory Vegetarian (green circle in green square) or Non-Vegetarian (brown triangle in brown square) logo conforming to PDP surface area millimeter dimensions.', 'measurement', 'MAJOR', 'Display the compliant Veg (green circle in green square) or Non-Veg (brown triangle in brown square) symbol meeting minimum PDP millimeter dimensions.', '{"pdp_sizing_mm": {"<=100": 6.0, "<=500": 8.0, "<=2500": 10.0, ">2500": 16.0}}'::jsonb) ON CONFLICT (rule_id) DO UPDATE SET rule_citation = EXCLUDED.rule_citation, description = EXCLUDED.description, severity = EXCLUDED.severity, fix_suggestion = EXCLUDED.fix_suggestion, validation_logic = EXCLUDED.validation_logic;
INSERT INTO rule_definitions (rule_id, rule_citation, description, check_type, severity, fix_suggestion, validation_logic) VALUES ('fssai_check_4', 'FSSAI 2020 Reg 5(1) / Ingredients', 'List of Ingredients in strictly descending order of weight or volume at manufacture with Quantitative Ingredient Declaration (QUID) monotonicity.', 'presence', 'MAJOR', 'List all ingredients in strictly descending order of incoming weight/volume, ensuring declared percentages descend monotonically.', '{"descending_order_enforced": true}'::jsonb) ON CONFLICT (rule_id) DO UPDATE SET rule_citation = EXCLUDED.rule_citation, description = EXCLUDED.description, severity = EXCLUDED.severity, fix_suggestion = EXCLUDED.fix_suggestion, validation_logic = EXCLUDED.validation_logic;
INSERT INTO rule_definitions (rule_id, rule_citation, description, check_type, severity, fix_suggestion, validation_logic) VALUES ('fssai_check_5', 'FSSAI 2020 Reg 5(2) / Allergens', 'Mandatory separate allergen declaration (''Contains: ...'') for 8 statutory allergen classes (gluten, crustaceans, milk, eggs, fish, nuts, soy, sulphites).', 'presence', 'CRITICAL', 'Add a separate allergen advisory statement immediately adjacent to ingredients (e.g. ''Contains: Wheat (Gluten), Milk, Tree Nuts'').', '{"allergen_classes": ["gluten", "crustaceans", "milk", "eggs", "fish", "nuts", "soy", "sulphites"]}'::jsonb) ON CONFLICT (rule_id) DO UPDATE SET rule_citation = EXCLUDED.rule_citation, description = EXCLUDED.description, severity = EXCLUDED.severity, fix_suggestion = EXCLUDED.fix_suggestion, validation_logic = EXCLUDED.validation_logic;
INSERT INTO rule_definitions (rule_id, rule_citation, description, check_type, severity, fix_suggestion, validation_logic) VALUES ('fssai_check_6', 'FSSAI 2020 Reg 5(10) / Expiry Date', 'Mandatory Expiry Date or Use By date declaration. ''Best Before'' date is optional and cannot substitute for an explicit Expiry Date.', 'regex', 'CRITICAL', 'Declare an explicit ''Expiry Date'' or ''Use By'' date on the package (e.g. ''Expiry: 31/12/2026''). ''Best Before'' is not a legal substitute.', '{"mandatory_keywords": ["expiry", "use by", "exp"]}'::jsonb) ON CONFLICT (rule_id) DO UPDATE SET rule_citation = EXCLUDED.rule_citation, description = EXCLUDED.description, severity = EXCLUDED.severity, fix_suggestion = EXCLUDED.fix_suggestion, validation_logic = EXCLUDED.validation_logic;
INSERT INTO rule_definitions (rule_id, rule_citation, description, check_type, severity, fix_suggestion, validation_logic) VALUES ('apparel_check_1', 'Textile Rule / Fiber 100% Math', 'Mandatory declaration of fiber/fabric names with exact percentage values mathematically totaling 100%.', 'measurement', 'CRITICAL', 'Declare all component fibers and fabrics with percentage values that sum exactly to 100% (e.g. ''60% Cotton, 40% Polyester'').', '{"exact_sum": 100.0}'::jsonb) ON CONFLICT (rule_id) DO UPDATE SET rule_citation = EXCLUDED.rule_citation, description = EXCLUDED.description, severity = EXCLUDED.severity, fix_suggestion = EXCLUDED.fix_suggestion, validation_logic = EXCLUDED.validation_logic;
INSERT INTO rule_definitions (rule_id, rule_citation, description, check_type, severity, fix_suggestion, validation_logic) VALUES ('apparel_check_2', 'Rule 6(1)(c) / Size & Metric', 'Garment size must declare physical metric dimensions in centimeters (cm) or meters (m); international letter size (S/M/L/XL) alone is legally insufficient.', 'measurement', 'CRITICAL', 'Pair international letter sizes (S/M/L/XL) with physical metric measurements in centimeters (e.g. ''Size: L (Chest 102 cm, Length 76 cm)'').', '{"metric_pairing_required": true}'::jsonb) ON CONFLICT (rule_id) DO UPDATE SET rule_citation = EXCLUDED.rule_citation, description = EXCLUDED.description, severity = EXCLUDED.severity, fix_suggestion = EXCLUDED.fix_suggestion, validation_logic = EXCLUDED.validation_logic;
INSERT INTO rule_definitions (rule_id, rule_citation, description, check_type, severity, fix_suggestion, validation_logic) VALUES ('apparel_check_3', 'Rule 6(1)(e) / MRP & Tax Suffix', 'Maximum Retail Price in INR/Rupees explicitly accompanied by mandatory ''inclusive of all taxes'' suffix with OCR typo tolerance.', 'regex', 'CRITICAL', 'Include the mandatory statutory suffix ''inclusive of all taxes'' or ''incl. of all taxes'' immediately adjacent to the MRP declaration.', '{"required_phrases": ["inclusive of all taxes", "incl. of all taxes"]}'::jsonb) ON CONFLICT (rule_id) DO UPDATE SET rule_citation = EXCLUDED.rule_citation, description = EXCLUDED.description, severity = EXCLUDED.severity, fix_suggestion = EXCLUDED.fix_suggestion, validation_logic = EXCLUDED.validation_logic;
INSERT INTO rule_definitions (rule_id, rule_citation, description, check_type, severity, fix_suggestion, validation_logic) VALUES ('apparel_check_4', 'Rule 6(1)(b) / Apparel Taxonomy', 'Common or generic apparel commodity name must match recognized national Department of Consumer Affairs taxonomy (>=80% similarity).', 'presence', 'MAJOR', 'Declare the statutory generic apparel commodity name (e.g. ''Men''s T-Shirt'', ''Formal Trousers'', ''Cotton Saree'') separate from brand name.', '{"taxonomy_threshold": 80}'::jsonb) ON CONFLICT (rule_id) DO UPDATE SET rule_citation = EXCLUDED.rule_citation, description = EXCLUDED.description, severity = EXCLUDED.severity, fix_suggestion = EXCLUDED.fix_suggestion, validation_logic = EXCLUDED.validation_logic;
INSERT INTO rule_definitions (rule_id, rule_citation, description, check_type, severity, fix_suggestion, validation_logic) VALUES ('apparel_check_5', 'Rule 6(1)(f) / Consumer Care 3-Way', 'All 3 mandatory consumer care channels must be present: working telephone helpline, valid email, and physical postal address with 6-digit PIN code.', 'presence', 'CRITICAL', 'Provide all 3 statutory consumer care channels: working telephone number (or 1800 toll-free), valid email ID, and postal address with 6-digit PIN code.', '{"required_channels": ["phone", "email", "address"]}'::jsonb) ON CONFLICT (rule_id) DO UPDATE SET rule_citation = EXCLUDED.rule_citation, description = EXCLUDED.description, severity = EXCLUDED.severity, fix_suggestion = EXCLUDED.fix_suggestion, validation_logic = EXCLUDED.validation_logic;
INSERT INTO rule_definitions (rule_id, rule_citation, description, check_type, severity, fix_suggestion, validation_logic) VALUES ('apparel_check_6', 'Rule 6(1)(d) / Contextual MFD', 'Month and year of manufacture or pre-packing declared in explicit statutory context (MFD / MFG / PKD / Packed).', 'regex', 'MAJOR', 'Declare the manufacturing or packing date in explicit statutory context (e.g. ''MFD: 08/2026'' or ''PKD: Aug 2026'').', '{"context_keywords": ["mfd", "mfg", "pkd", "packed", "manufactured"]}'::jsonb) ON CONFLICT (rule_id) DO UPDATE SET rule_citation = EXCLUDED.rule_citation, description = EXCLUDED.description, severity = EXCLUDED.severity, fix_suggestion = EXCLUDED.fix_suggestion, validation_logic = EXCLUDED.validation_logic;
INSERT INTO rule_definitions (rule_id, rule_citation, description, check_type, severity, fix_suggestion, validation_logic) VALUES ('apparel_check_7', 'Rule 6(1)(f) / Country of Origin', 'Explicit Country of Origin declaration (''Country of Origin: ...'' or ''Made in ...'') separate from general manufacturer address mentions.', 'presence', 'CRITICAL', 'Include an explicit Country of Origin declaration (e.g. ''Country of Origin: India'' or ''Made in India'') on the garment label.', '{"explicit_context_required": true}'::jsonb) ON CONFLICT (rule_id) DO UPDATE SET rule_citation = EXCLUDED.rule_citation, description = EXCLUDED.description, severity = EXCLUDED.severity, fix_suggestion = EXCLUDED.fix_suggestion, validation_logic = EXCLUDED.validation_logic;

-- SEEDING 74 VERIFIED MANUFACTURER CACHES
INSERT INTO manufacturer_cache (company_name, aliases, registered_pincodes, verified_addresses) VALUES ('Raymond Limited', '["Raymond", "Park Avenue", "ColorPlus", "Parx"]'::jsonb, '["400606", "400001"]'::jsonb, '["Plot No. 156/H No. 2, Village Zadgaon, Ratnagiri, Maharashtra 415612", "Jekegram, Pokhran Road No. 1, Thane West 400606"]'::jsonb);
INSERT INTO manufacturer_cache (company_name, aliases, registered_pincodes, verified_addresses) VALUES ('Aditya Birla Fashion and Retail Limited', '["ABFRL", "Louis Philippe", "Van Heusen", "Allen Solly", "Peter England"]'::jsonb, '["560068", "400025"]'::jsonb, '["Piramal Agastya Corporate Park, Building ''A'', 4th and 5th Floor, Unit No. 401, 403, 501, 502, L.B.S. Road, Kurla West, Mumbai 400070"]'::jsonb);
INSERT INTO manufacturer_cache (company_name, aliases, registered_pincodes, verified_addresses) VALUES ('Arvind Limited', '["Arvind", "Flying Machine", "US Polo"]'::jsonb, '["380025"]'::jsonb, '["Naroda Road, Ahmedabad, Gujarat 380025"]'::jsonb);
INSERT INTO manufacturer_cache (company_name, aliases, registered_pincodes, verified_addresses) VALUES ('Page Industries Limited (Jockey)', '["Jockey", "Page"]'::jsonb, '["560008"]'::jsonb, '["Umiya Business Bay - Tower 1, 7th Floor, Cessna Business Park, Kadubeesanahalli, Bangalore 560103"]'::jsonb);
INSERT INTO manufacturer_cache (company_name, aliases, registered_pincodes, verified_addresses) VALUES ('Indian Brands Co. 11', '["indian brands 11", "brand_co_11"]'::jsonb, '["110011", "400011"]'::jsonb, '["Building No. 11, Industrial Area, Sector 2, New Delhi - 110011"]'::jsonb);
INSERT INTO manufacturer_cache (company_name, aliases, registered_pincodes, verified_addresses) VALUES ('Indian Brands Co. 12', '["indian brands 12", "brand_co_12"]'::jsonb, '["110012", "400012"]'::jsonb, '["Building No. 12, Industrial Area, Sector 3, New Delhi - 110012"]'::jsonb);
INSERT INTO manufacturer_cache (company_name, aliases, registered_pincodes, verified_addresses) VALUES ('Indian Brands Co. 13', '["indian brands 13", "brand_co_13"]'::jsonb, '["110013", "400013"]'::jsonb, '["Building No. 13, Industrial Area, Sector 4, New Delhi - 110013"]'::jsonb);
INSERT INTO manufacturer_cache (company_name, aliases, registered_pincodes, verified_addresses) VALUES ('Indian Brands Co. 14', '["indian brands 14", "brand_co_14"]'::jsonb, '["110014", "400014"]'::jsonb, '["Building No. 14, Industrial Area, Sector 5, New Delhi - 110014"]'::jsonb);
INSERT INTO manufacturer_cache (company_name, aliases, registered_pincodes, verified_addresses) VALUES ('Indian Brands Co. 15', '["indian brands 15", "brand_co_15"]'::jsonb, '["110015", "400015"]'::jsonb, '["Building No. 15, Industrial Area, Sector 6, New Delhi - 110015"]'::jsonb);
INSERT INTO manufacturer_cache (company_name, aliases, registered_pincodes, verified_addresses) VALUES ('Indian Brands Co. 16', '["indian brands 16", "brand_co_16"]'::jsonb, '["110016", "400016"]'::jsonb, '["Building No. 16, Industrial Area, Sector 7, New Delhi - 110016"]'::jsonb);
INSERT INTO manufacturer_cache (company_name, aliases, registered_pincodes, verified_addresses) VALUES ('Indian Brands Co. 17', '["indian brands 17", "brand_co_17"]'::jsonb, '["110017", "400017"]'::jsonb, '["Building No. 17, Industrial Area, Sector 8, New Delhi - 110017"]'::jsonb);
INSERT INTO manufacturer_cache (company_name, aliases, registered_pincodes, verified_addresses) VALUES ('Indian Brands Co. 18', '["indian brands 18", "brand_co_18"]'::jsonb, '["110018", "400018"]'::jsonb, '["Building No. 18, Industrial Area, Sector 9, New Delhi - 110018"]'::jsonb);
INSERT INTO manufacturer_cache (company_name, aliases, registered_pincodes, verified_addresses) VALUES ('Indian Brands Co. 19', '["indian brands 19", "brand_co_19"]'::jsonb, '["110019", "400019"]'::jsonb, '["Building No. 19, Industrial Area, Sector 10, New Delhi - 110019"]'::jsonb);
INSERT INTO manufacturer_cache (company_name, aliases, registered_pincodes, verified_addresses) VALUES ('Indian Brands Co. 20', '["indian brands 20", "brand_co_20"]'::jsonb, '["110020", "400020"]'::jsonb, '["Building No. 20, Industrial Area, Sector 1, New Delhi - 110020"]'::jsonb);
INSERT INTO manufacturer_cache (company_name, aliases, registered_pincodes, verified_addresses) VALUES ('Indian Brands Co. 21', '["indian brands 21", "brand_co_21"]'::jsonb, '["110021", "400021"]'::jsonb, '["Building No. 21, Industrial Area, Sector 2, New Delhi - 110021"]'::jsonb);
INSERT INTO manufacturer_cache (company_name, aliases, registered_pincodes, verified_addresses) VALUES ('Indian Brands Co. 22', '["indian brands 22", "brand_co_22"]'::jsonb, '["110022", "400022"]'::jsonb, '["Building No. 22, Industrial Area, Sector 3, New Delhi - 110022"]'::jsonb);
INSERT INTO manufacturer_cache (company_name, aliases, registered_pincodes, verified_addresses) VALUES ('Indian Brands Co. 23', '["indian brands 23", "brand_co_23"]'::jsonb, '["110023", "400023"]'::jsonb, '["Building No. 23, Industrial Area, Sector 4, New Delhi - 110023"]'::jsonb);
INSERT INTO manufacturer_cache (company_name, aliases, registered_pincodes, verified_addresses) VALUES ('Indian Brands Co. 24', '["indian brands 24", "brand_co_24"]'::jsonb, '["110024", "400024"]'::jsonb, '["Building No. 24, Industrial Area, Sector 5, New Delhi - 110024"]'::jsonb);
INSERT INTO manufacturer_cache (company_name, aliases, registered_pincodes, verified_addresses) VALUES ('Indian Brands Co. 25', '["indian brands 25", "brand_co_25"]'::jsonb, '["110025", "400025"]'::jsonb, '["Building No. 25, Industrial Area, Sector 6, New Delhi - 110025"]'::jsonb);
INSERT INTO manufacturer_cache (company_name, aliases, registered_pincodes, verified_addresses) VALUES ('Indian Brands Co. 26', '["indian brands 26", "brand_co_26"]'::jsonb, '["110026", "400026"]'::jsonb, '["Building No. 26, Industrial Area, Sector 7, New Delhi - 110026"]'::jsonb);
INSERT INTO manufacturer_cache (company_name, aliases, registered_pincodes, verified_addresses) VALUES ('Indian Brands Co. 27', '["indian brands 27", "brand_co_27"]'::jsonb, '["110027", "400027"]'::jsonb, '["Building No. 27, Industrial Area, Sector 8, New Delhi - 110027"]'::jsonb);
INSERT INTO manufacturer_cache (company_name, aliases, registered_pincodes, verified_addresses) VALUES ('Indian Brands Co. 28', '["indian brands 28", "brand_co_28"]'::jsonb, '["110028", "400028"]'::jsonb, '["Building No. 28, Industrial Area, Sector 9, New Delhi - 110028"]'::jsonb);
INSERT INTO manufacturer_cache (company_name, aliases, registered_pincodes, verified_addresses) VALUES ('Indian Brands Co. 29', '["indian brands 29", "brand_co_29"]'::jsonb, '["110029", "400029"]'::jsonb, '["Building No. 29, Industrial Area, Sector 10, New Delhi - 110029"]'::jsonb);
INSERT INTO manufacturer_cache (company_name, aliases, registered_pincodes, verified_addresses) VALUES ('Indian Brands Co. 30', '["indian brands 30", "brand_co_30"]'::jsonb, '["110030", "400030"]'::jsonb, '["Building No. 30, Industrial Area, Sector 1, New Delhi - 110030"]'::jsonb);
INSERT INTO manufacturer_cache (company_name, aliases, registered_pincodes, verified_addresses) VALUES ('Indian Brands Co. 31', '["indian brands 31", "brand_co_31"]'::jsonb, '["110031", "400031"]'::jsonb, '["Building No. 31, Industrial Area, Sector 2, New Delhi - 110031"]'::jsonb);
INSERT INTO manufacturer_cache (company_name, aliases, registered_pincodes, verified_addresses) VALUES ('Indian Brands Co. 32', '["indian brands 32", "brand_co_32"]'::jsonb, '["110032", "400032"]'::jsonb, '["Building No. 32, Industrial Area, Sector 3, New Delhi - 110032"]'::jsonb);
INSERT INTO manufacturer_cache (company_name, aliases, registered_pincodes, verified_addresses) VALUES ('Indian Brands Co. 33', '["indian brands 33", "brand_co_33"]'::jsonb, '["110033", "400033"]'::jsonb, '["Building No. 33, Industrial Area, Sector 4, New Delhi - 110033"]'::jsonb);
INSERT INTO manufacturer_cache (company_name, aliases, registered_pincodes, verified_addresses) VALUES ('Indian Brands Co. 34', '["indian brands 34", "brand_co_34"]'::jsonb, '["110034", "400034"]'::jsonb, '["Building No. 34, Industrial Area, Sector 5, New Delhi - 110034"]'::jsonb);
INSERT INTO manufacturer_cache (company_name, aliases, registered_pincodes, verified_addresses) VALUES ('Indian Brands Co. 35', '["indian brands 35", "brand_co_35"]'::jsonb, '["110035", "400035"]'::jsonb, '["Building No. 35, Industrial Area, Sector 6, New Delhi - 110035"]'::jsonb);
INSERT INTO manufacturer_cache (company_name, aliases, registered_pincodes, verified_addresses) VALUES ('Indian Brands Co. 36', '["indian brands 36", "brand_co_36"]'::jsonb, '["110036", "400036"]'::jsonb, '["Building No. 36, Industrial Area, Sector 7, New Delhi - 110036"]'::jsonb);
INSERT INTO manufacturer_cache (company_name, aliases, registered_pincodes, verified_addresses) VALUES ('Indian Brands Co. 37', '["indian brands 37", "brand_co_37"]'::jsonb, '["110037", "400037"]'::jsonb, '["Building No. 37, Industrial Area, Sector 8, New Delhi - 110037"]'::jsonb);
INSERT INTO manufacturer_cache (company_name, aliases, registered_pincodes, verified_addresses) VALUES ('Indian Brands Co. 38', '["indian brands 38", "brand_co_38"]'::jsonb, '["110038", "400038"]'::jsonb, '["Building No. 38, Industrial Area, Sector 9, New Delhi - 110038"]'::jsonb);
INSERT INTO manufacturer_cache (company_name, aliases, registered_pincodes, verified_addresses) VALUES ('ITC Limited', '["ITC"]'::jsonb, '["700071"]'::jsonb, '["Virginia House, 37 J.L. Nehru Road, Kolkata 700071"]'::jsonb);
INSERT INTO manufacturer_cache (company_name, aliases, registered_pincodes, verified_addresses) VALUES ('Indian Brands Co. 39', '["indian brands 39", "brand_co_39"]'::jsonb, '["110039", "400039"]'::jsonb, '["Building No. 39, Industrial Area, Sector 10, New Delhi - 110039"]'::jsonb);
INSERT INTO manufacturer_cache (company_name, aliases, registered_pincodes, verified_addresses) VALUES ('Indian Brands Co. 40', '["indian brands 40", "brand_co_40"]'::jsonb, '["110040", "400040"]'::jsonb, '["Building No. 40, Industrial Area, Sector 1, New Delhi - 110040"]'::jsonb);
INSERT INTO manufacturer_cache (company_name, aliases, registered_pincodes, verified_addresses) VALUES ('Indian Brands Co. 41', '["indian brands 41", "brand_co_41"]'::jsonb, '["110041", "400041"]'::jsonb, '["Building No. 41, Industrial Area, Sector 2, New Delhi - 110041"]'::jsonb);
INSERT INTO manufacturer_cache (company_name, aliases, registered_pincodes, verified_addresses) VALUES ('Indian Brands Co. 42', '["indian brands 42", "brand_co_42"]'::jsonb, '["110042", "400042"]'::jsonb, '["Building No. 42, Industrial Area, Sector 3, New Delhi - 110042"]'::jsonb);
INSERT INTO manufacturer_cache (company_name, aliases, registered_pincodes, verified_addresses) VALUES ('Indian Brands Co. 43', '["indian brands 43", "brand_co_43"]'::jsonb, '["110043", "400043"]'::jsonb, '["Building No. 43, Industrial Area, Sector 4, New Delhi - 110043"]'::jsonb);
INSERT INTO manufacturer_cache (company_name, aliases, registered_pincodes, verified_addresses) VALUES ('Indian Brands Co. 44', '["indian brands 44", "brand_co_44"]'::jsonb, '["110044", "400044"]'::jsonb, '["Building No. 44, Industrial Area, Sector 5, New Delhi - 110044"]'::jsonb);
INSERT INTO manufacturer_cache (company_name, aliases, registered_pincodes, verified_addresses) VALUES ('Indian Brands Co. 45', '["indian brands 45", "brand_co_45"]'::jsonb, '["110045", "400045"]'::jsonb, '["Building No. 45, Industrial Area, Sector 6, New Delhi - 110045"]'::jsonb);
INSERT INTO manufacturer_cache (company_name, aliases, registered_pincodes, verified_addresses) VALUES ('Indian Brands Co. 46', '["indian brands 46", "brand_co_46"]'::jsonb, '["110046", "400046"]'::jsonb, '["Building No. 46, Industrial Area, Sector 7, New Delhi - 110046"]'::jsonb);
INSERT INTO manufacturer_cache (company_name, aliases, registered_pincodes, verified_addresses) VALUES ('Indian Brands Co. 47', '["indian brands 47", "brand_co_47"]'::jsonb, '["110047", "400047"]'::jsonb, '["Building No. 47, Industrial Area, Sector 8, New Delhi - 110047"]'::jsonb);
INSERT INTO manufacturer_cache (company_name, aliases, registered_pincodes, verified_addresses) VALUES ('Indian Brands Co. 48', '["indian brands 48", "brand_co_48"]'::jsonb, '["110048", "400048"]'::jsonb, '["Building No. 48, Industrial Area, Sector 9, New Delhi - 110048"]'::jsonb);
INSERT INTO manufacturer_cache (company_name, aliases, registered_pincodes, verified_addresses) VALUES ('Indian Brands Co. 49', '["indian brands 49", "brand_co_49"]'::jsonb, '["110049", "400049"]'::jsonb, '["Building No. 49, Industrial Area, Sector 10, New Delhi - 110049"]'::jsonb);
INSERT INTO manufacturer_cache (company_name, aliases, registered_pincodes, verified_addresses) VALUES ('Indian Brands Co. 50', '["indian brands 50", "brand_co_50"]'::jsonb, '["110050", "400050"]'::jsonb, '["Building No. 50, Industrial Area, Sector 1, New Delhi - 110050"]'::jsonb);
INSERT INTO manufacturer_cache (company_name, aliases, registered_pincodes, verified_addresses) VALUES ('Hindustan Unilever Limited', '["HUL", "Unilever"]'::jsonb, '["400099", "400020"]'::jsonb, '["Unilever House, B. D. Sawant Marg, Chakala, Andheri East, Mumbai 400099"]'::jsonb);
INSERT INTO manufacturer_cache (company_name, aliases, registered_pincodes, verified_addresses) VALUES ('Tata Consumer Products Limited', '["Tata Tea", "Tata Salt", "TCPL"]'::jsonb, '["700020", "560001"]'::jsonb, '["1, Bishop Lefroy Road, Kolkata 700020"]'::jsonb);
INSERT INTO manufacturer_cache (company_name, aliases, registered_pincodes, verified_addresses) VALUES ('Nestle India Limited', '["Nestle"]'::jsonb, '["122002"]'::jsonb, '["100 / 101, World Trade Centre, Barakhamba Lane, New Delhi 110001", "Nestle House, Jacaranda Marg, M Block, DLF City Phase II, Gurugram 122002"]'::jsonb);
INSERT INTO manufacturer_cache (company_name, aliases, registered_pincodes, verified_addresses) VALUES ('Britannia Industries Limited', '["Britannia"]'::jsonb, '["560048", "700017"]'::jsonb, '["5/1A, Hungerford Street, Kolkata 700017", "Prestige Shantiniketan, Whitefield, Bangalore 560048"]'::jsonb);
INSERT INTO manufacturer_cache (company_name, aliases, registered_pincodes, verified_addresses) VALUES ('Parle Products Private Limited', '["Parle", "Parle-G"]'::jsonb, '["400057"]'::jsonb, '["North Level Crossing, Vile Parle East, Mumbai 400057"]'::jsonb);
INSERT INTO manufacturer_cache (company_name, aliases, registered_pincodes, verified_addresses) VALUES ('Dabur India Limited', '["Dabur"]'::jsonb, '["201010", "110002"]'::jsonb, '["8/3, Asaf Ali Road, New Delhi 110002", "Kaushambi, Sahibabad, Ghaziabad 201010"]'::jsonb);
INSERT INTO manufacturer_cache (company_name, aliases, registered_pincodes, verified_addresses) VALUES ('Marico Limited', '["Marico", "Parachute"]'::jsonb, '["400098"]'::jsonb, '["7th Floor, Grande Palladium, 175, CST Road, Kalina, Santacruz East, Mumbai 400098"]'::jsonb);
INSERT INTO manufacturer_cache (company_name, aliases, registered_pincodes, verified_addresses) VALUES ('Amul (GCMMF)', '["Amul", "GCMMF"]'::jsonb, '["388001"]'::jsonb, '["Amul Dairy Road, Anand 388001, Gujarat"]'::jsonb);
INSERT INTO manufacturer_cache (company_name, aliases, registered_pincodes, verified_addresses) VALUES ('Bisleri International Private Limited', '["Bisleri"]'::jsonb, '["400099"]'::jsonb, '["Western Express Highway, Andheri East, Mumbai 400099"]'::jsonb);
INSERT INTO manufacturer_cache (company_name, aliases, registered_pincodes, verified_addresses) VALUES ('Godrej Consumer Products Limited', '["GCPL", "Godrej"]'::jsonb, '["400079"]'::jsonb, '["Godrej One, Pirojshanagar, Eastern Express Highway, Vikhroli East, Mumbai 400079"]'::jsonb);
INSERT INTO manufacturer_cache (company_name, aliases, registered_pincodes, verified_addresses) VALUES ('Colgate-Palmolive (India) Limited', '["Colgate"]'::jsonb, '["400076"]'::jsonb, '["Colgate Research Centre, Main Street, Hiranandani Gardens, Powai, Mumbai 400076"]'::jsonb);
INSERT INTO manufacturer_cache (company_name, aliases, registered_pincodes, verified_addresses) VALUES ('Mother Dairy Fruit & Vegetable Pvt Ltd', '["Mother Dairy"]'::jsonb, '["110092"]'::jsonb, '["Patparganj, Delhi 110092"]'::jsonb);
INSERT INTO manufacturer_cache (company_name, aliases, registered_pincodes, verified_addresses) VALUES ('Haldiram Snacks Private Limited', '["Haldiram", "Haldirams"]'::jsonb, '["201307", "440008"]'::jsonb, '["B-1/H-8, Mohan Co-operative Industrial Estate, Main Mathura Road, New Delhi 110044"]'::jsonb);
INSERT INTO manufacturer_cache (company_name, aliases, registered_pincodes, verified_addresses) VALUES ('Bikaji Foods International Limited', '["Bikaji"]'::jsonb, '["334006"]'::jsonb, '["F 196-199, F 178 & E 188, Bichhwal Industrial Area, Bikaner 334006"]'::jsonb);
INSERT INTO manufacturer_cache (company_name, aliases, registered_pincodes, verified_addresses) VALUES ('Balaji Wafers Private Limited', '["Balaji"]'::jsonb, '["360024"]'::jsonb, '["Vajdi (Vad), Kalawad Road, Tal. Lodhika, Dist. Rajkot 360024"]'::jsonb);
INSERT INTO manufacturer_cache (company_name, aliases, registered_pincodes, verified_addresses) VALUES ('Patanjali Ayurved Limited', '["Patanjali"]'::jsonb, '["249405"]'::jsonb, '["Patanjali Food & Herbal Park, Padartha, Laksar Road, Haridwar 249405"]'::jsonb);
INSERT INTO manufacturer_cache (company_name, aliases, registered_pincodes, verified_addresses) VALUES ('Emami Limited', '["Emami", "BoroPlus", "Zandu"]'::jsonb, '["700107"]'::jsonb, '["Emami Tower, 687 Anandapur, EM Bypass, Kolkata 700107"]'::jsonb);
INSERT INTO manufacturer_cache (company_name, aliases, registered_pincodes, verified_addresses) VALUES ('Adani Wilmar Limited', '["Fortune", "Adani Wilmar"]'::jsonb, '["380009"]'::jsonb, '["Fortune House, Near Navrangpura Railway Crossing, Ahmedabad 380009"]'::jsonb);
INSERT INTO manufacturer_cache (company_name, aliases, registered_pincodes, verified_addresses) VALUES ('PepsiCo India Holdings Private Limited', '["PepsiCo", "Lays", "Kurkure", "Tropicana"]'::jsonb, '["122002"]'::jsonb, '["Level 3-6, Pioneer Square, Sector 62, Near Golf Course Extension Road, Gurugram 122102"]'::jsonb);
INSERT INTO manufacturer_cache (company_name, aliases, registered_pincodes, verified_addresses) VALUES ('Coca-Cola India Private Limited', '["Coca-Cola", "Coke", "Thums Up"]'::jsonb, '["122016"]'::jsonb, '["One Horizon Center, Golf Course Road, DLF Phase 5, Sector 43, Gurugram 122003"]'::jsonb);
INSERT INTO manufacturer_cache (company_name, aliases, registered_pincodes, verified_addresses) VALUES ('Mondelez India Foods Private Limited', '["Cadbury", "Mondelez", "Oreo"]'::jsonb, '["400018"]'::jsonb, '["Unit No. 2001, 20th Floor, Tower-3, One International Center, Parel, Mumbai 400013"]'::jsonb);
INSERT INTO manufacturer_cache (company_name, aliases, registered_pincodes, verified_addresses) VALUES ('Reckitt Benckiser (India) Private Limited', '["Dettol", "Reckitt", "Harpic", "Lizol"]'::jsonb, '["122016"]'::jsonb, '["DLF Cyber Park, 6th & 7th Floor, Tower C, 405 B, Udyog Vihar Phase III, Sector 20, Gurugram 122016"]'::jsonb);
INSERT INTO manufacturer_cache (company_name, aliases, registered_pincodes, verified_addresses) VALUES ('Procter & Gamble Hygiene and Health Care Limited', '["P&G", "Gillette", "Pampers", "Ariel", "Tide"]'::jsonb, '["400099"]'::jsonb, '["P&G Plaza, Cardinal Gracias Road, Chakala, Andheri East, Mumbai 400099"]'::jsonb);
INSERT INTO manufacturer_cache (company_name, aliases, registered_pincodes, verified_addresses) VALUES ('Johnson & Johnson Private Limited', '["J&J", "Johnson & Johnson", "Johnsons"]'::jsonb, '["400080"]'::jsonb, '["501 Arena Space, Behind Majas Bus Depot, Off JVLR, Jogeshwari East, Mumbai 400060"]'::jsonb);
INSERT INTO manufacturer_cache (company_name, aliases, registered_pincodes, verified_addresses) VALUES ('GSK Consumer Healthcare (Haleon India)', '["Sensodyne", "Crocin", "Eno", "Haleon"]'::jsonb, '["122002"]'::jsonb, '["5th Floor, DLF Cyber City, Building 10, Tower C, DLF Phase 2, Gurugram 122002"]'::jsonb);
INSERT INTO manufacturer_cache (company_name, aliases, registered_pincodes, verified_addresses) VALUES ('Wipro Consumer Care and Lighting', '["Wipro", "Santoor", "Yardley"]'::jsonb, '["560035"]'::jsonb, '["Doddakannelli, Sarjapur Road, Bangalore 560035"]'::jsonb);
INSERT INTO manufacturer_cache (company_name, aliases, registered_pincodes, verified_addresses) VALUES ('CavinKare Private Limited', '["CavinKare", "Chik", "Meera", "Nyle"]'::jsonb, '["600032"]'::jsonb, '["Cavin Ville, No. 12, Cenotaph Road, Teynampet, Chennai 600018"]'::jsonb);
INSERT INTO manufacturer_cache (company_name, aliases, registered_pincodes, verified_addresses) VALUES ('Jyothy Labs Limited', '["Ujala", "Pril", "Margo", "Exo", "Jyothy"]'::jsonb, '["400059"]'::jsonb, '["Ujala House, Ram Krishna Mandir Road, Kondivita, Andheri East, Mumbai 400059"]'::jsonb);
INSERT INTO manufacturer_cache (company_name, aliases, registered_pincodes, verified_addresses) VALUES ('Himalaya Wellness Company', '["Himalaya", "Himalaya Herbals"]'::jsonb, '["562123"]'::jsonb, '["Makali, Bengaluru 562123, Karnataka"]'::jsonb);
